configVersionPleaseDoNotChange: 6

discord:
  token: '<your bot token>'
  generalprefix: ';;'
  ownerid: '<your user ID>'
  clientid: '<your bot client id>'
  clientsecret: '<your bot client secret>'
  disabledcommands:
  # globalcommandratelimit:
  #   burst: 1
  #   limitseconds: 10

permissions:
  defaultuserrules:
    - +sp.etc.*
    - +sp.chat.*
  defaultadminrules:
    - +sp.guild.*
    - +sp.etc.*
    - +sp.chat.*

database:
  type: mysql
  mysql:
    host: 'localhost:3306'
    user: 'root'
    database: 'shinpuru'
    password: 'dev'

cache:
  redis:
    addr: 'localhost:6379'
    type: 0
  cachedatabase: true
  lifetimes:
    general: 30d
    member: 90d
    user: 90d

storage:
  type: file
  file:
    location: ./data
  # minio:
  #   endpoint: "localhost:9000"
  #   accesskey: "dev-access-key"
  #   accesssecret: "dev-secret-key"
  #   secure: true

logging:
  commandlogging: true
  loglevel: 5

twitchapp:
  clientid: ''
  clientsecret: ''

webserver:
  enabled: true
  addr: :8080
  apitokenkey: '12345678901234567890123456789012'
  tls:
    enabled: false
  publicaddr: http://localhost:8080
  debugpublicaddr: http://localhost:8081
  ratelimit:
    enabled: false
    burst: 50
    limitseconds: 3
  captcha:
    sitekey: '20000000-ffff-ffff-ffff-000000000002'
    secretkey: '0x0000000000000000000000000000000000000000'

# metrics:
#   enable: true
#   addr: ":9091"

privacy:
  noticeurl: test
  contact:
    - title: test
      value: test
