name: Web CI

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "web/**"
  pull_request:
    types:
      - opened
      - reopened
      - edited
    paths:
      - "web/**"

jobs:
  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: 'web'
        run: yarn
      - name: ESLint
        working-directory: 'web'
        run: yarn lint
